### ISSUE TITLE
Related code for experiments

### ISSUE THREAD

**Issue by jimo17** [kylemin/HEX-graph#4]
Hi, thank you very much for open sourcing. I am very interested in your experiments. Could you please share the code of your experiments on imagenet-2012 and cifar100? I would appreciate it if you could share the relevant code.

**Comment by kylemin** [comment]
Hi,

Thank you for your interest!
Unfortunately, I do not maintain the code that I used to run the experiments anymore. I hope the [Performance section](https://github.com/kylemin/HEX-graph#performance) gives you details of the experiments.

Thank you,
Kyle
